<?php 

/*
 * @Author: Cloudflying
 * @Date: 2022-06-19 02:17:09
 * @LastEditTime: 2023-10-22 13:14:58
 * @LastEditors: Cloudflying
 * @Description: 
 */

// archive 疑似归档重复的记录含最新记录归档
return [
    'db' => [
        'qqwry.dat' => 'http://mirrors.xieke.org/ip/qqwry/qqwry-2022-06-08.dat',
        'geolie2-country.tar.gz' => 'http://mirrors.xieke.org/ip/geolite2/GeoLite2-Country-20220618.tar.gz',
        'geolie2-country-csv.zip' => 'http://mirrors.xieke.org/ip/geolite2/GeoLite2-Country-CSV-20220618.zip',
        'geolie2-city.tar.gz' => 'http://mirrors.xieke.org/ip/geolite2/GeoLite2-City-20220618.tar.gz',
        'geolie2-city-csv.zip' => 'http://mirrors.xieke.org/ip/geolite2/GeoLite2-City-CSV-20220618.zip',
        'geolie2-asn-csv.zip' => 'http://mirrors.xieke.org/ip/geolite2/GeoLite2-ASN-CSV-20220618.zip',
        'geolie2-asn.tar.gz' => 'http://mirrors.xieke.org/ip/geolite2/GeoLite2-ASN-20220618.tar.gz',
        'ip2region.db' => 'http://mirrors.xieke.org/ip/ip2region/ip2region-20220618.db',
        'ip2location-lite-asn-csv.zip' => 'http://mirrors.xieke.org/ip/ip2location/IP2LOCATION-LITE-ASN.CSV-2022-06-18.ZIP',
        'ip2location-lite-asn-ipv6-csv.zip' => 'http://mirrors.xieke.org/ip/ip2location/IP2LOCATION-LITE-ASN.IPV6.CSV-2022-06-18.ZIP',
        'ip2location-lite-db11-ipv6-csv.zip' => 'http://mirrors.xieke.org/ip/ip2location/IP2LOCATION-LITE-DB11.IPV6.CSV-2022-06-18.ZIP',
        'ip2location-lite-db11-ipv6-csv.zip' => 'http://mirrors.xieke.org/ip/ip2location/IP2LOCATION-LITE-DB11.IPV6.BIN-2022-06-18.ZIP',
        'ip2location-lite-db11-csv.zip' => 'http://mirrors.xieke.org/ip/ip2location/IP2LOCATION-LITE-DB11.CSV-2022-06-18.ZIP',
        'ip2location-lite-db11-bin.zip' => 'http://mirrors.xieke.org/ip/ip2location/IP2LOCATION-LITE-DB11.BIN-2022-06-17.ZIP',
        'countrycodes.txt' => 'https://ftp.ripe.net/iso3166-countrycodes.txt',
        'dbip-asn.mmdb.gz' => 'http://mirrors.xieke.org/ip/dbip/dbip-asn-lite-20220601.mmdb.gz',
        'dbip-asn.csv.gz' => 'http://mirrors.xieke.org/ip/dbip/dbip-asn-lite-20220601.csv.gz',
        'dbip-city.mmdb.gz' => 'http://mirrors.xieke.org/ip/dbip/dbip-city-lite-20220601.mmdb.gz',
        'dbip-city.csv.gz' => 'http://mirrors.xieke.org/ip/dbip/dbip-city-lite-20220601.csv.gz',
        'dbip-country.mmdb.gz' => 'http://mirrors.xieke.org/ip/dbip/dbip-country-lite-20220601.mmdb.gz',
        'dbip-country.csv.gz' => 'http://mirrors.xieke.org/ip/dbip/dbip-country-lite-20220601.csv.gz',
        'ripe-asn-info'  => 'http://ftp.arin.net/info/asn.txt',
        'ripe-asn'  => 'https://ftp.ripe.net/ripe/asnames/asn.txt',
        'arin-transfers.json' => 'http://ftp.apnic.net/stats/arin/transfers/transfers_latest.json',
        'afrinic-transfers.json' => 'http://ftp.afrinic.net/stats/afrinic/transfers/transfers_latest.json',
        'apnic-transfers.json' => 'http://ftp.apnic.net/stats/apnic/transfers/transfers_latest.json',
        'lacnic-transfers.json' => 'http://ftp.apnic.net/stats/lacnic/transfers/transfers_latest.json',
        'ripencc-transfers.json' => 'http://ftp.apnic.net/stats/ripe-ncc/transfers/transfers_latest.json',
        'afrinic-transfers.json' => 'http://ftp.apnic.net/stats/afrinic/transfers/transfers_latest.json',
        'ripe-transfers.json' => 'https://ftp.ripe.net/ripe/stats/transfers/transfers_latest.json'
    ],
    'rir' => [
        'afrinic-delegated'  => 'https://bgp.potaroo.net/stats/afrinic/delegated',
        'delegated-afrinic-extended-latest'  => 'https://bgp.potaroo.net/stats/afrinic/delegated-extended',
        'delegated-afrinic-extended-latest'  => 'http://ftp.afrinic.net/stats/afrinic/delegated-afrinic-latest',
        'delegated-afrinic-extended-latest'  => 'https://bgp.potaroo.net/stats/afrinic/delegated-extended-latest',
        'delegated-afrinic-extended-latest'  => 'http://ftp.afrinic.net/stats/afrinic/delegated-afrinic-extended-latest',
        // 'afrinic-delegated-extended'  => 'https://bgp.potaroo.net/stats/afrinic/archive/2022/06/20220600-afrinic-delegated-extended',
        // 'ripecc-delegated-extended'  => 'https://bgp.potaroo.net/stats/ripencc/archive/2022/06/20220600-ripe-delegated-extended',
        // 'ripecc-delegated'  => 'https://bgp.potaroo.net/stats/ripencc/delegated',
        'ripecc-extended'  => 'https://bgp.potaroo.net/stats/ripencc/delegated-extended',
        // 'ripecc-delegated-new'  => 'https://bgp.potaroo.net/stats/ripencc/delegated-new',
        // 'ripe-delegated-ripencc-extended-latest'  => 'https://ftp.ripe.net/ripe/stats/delegated-ripencc-extended-latest',
        'ripe-delegated'  => 'https://bgp.potaroo.net/stats/ripe/delegated',
        // 'ripe-delegated-extended'  => 'https://bgp.potaroo.net/stats/ripe/delegated-extended',
        // 'ripe-delegated-new'  => 'https://bgp.potaroo.net/stats/ripe/delegated-new',
        // 'ripe-delegated-extended-archive'  => 'https://bgp.potaroo.net/stats/ripe/archive/2022/06/20220600-ripe-delegated-extended',
        // 'ripe-delegated-ripencc-latest'  => 'https://ftp.ripe.net/ripe/stats/delegated-ripencc-latest',
        'lacnic-delegated'  => 'https://bgp.potaroo.net/stats/lacnic/delegated',
        'lacnic-delegated-extended'  => 'https://bgp.potaroo.net/stats/lacnic/delegated-extended',
        'lacnic-delegated-extended-new'  => 'https://bgp.potaroo.net/stats/lacnic/delegated-extended-new',
        'iana-delegated'  => 'https://bgp.potaroo.net/stats/iana/delegated',
        // 'iana-delegated-extended'  => 'https://bgp.potaroo.net/stats/iana/delegated-extended',
        // 'iana-delegated-iana'  => 'https://bgp.potaroo.net/stats/iana/delegated-iana',
        // 'iana-delegated-iana-extended'  => 'https://bgp.potaroo.net/stats/iana/delegated-iana-extended',
        // 'iana-delegated-iana-latest'  => 'https://bgp.potaroo.net/stats/iana/delegated-iana-latest',
        // 'iana-delegated-iana-latest'  => 'http://ftp.apnic.net/stats/iana/delegated-iana-latest',
        // 'iana-delegated-txt'  => 'https://bgp.potaroo.net/stats/iana/delegated.txt',
        // 'nro-status-joint'  => 'https://bgp.potaroo.net/stats/nro/status.joint.txt',
        // 'nro-delegated-joint'  => 'https://bgp.potaroo.net/stats/nro/delegated.joint.txt',
        // 'nro-unallocated-joint'  => 'https://bgp.potaroo.net/stats/nro/unallocated.joint.txt',
        // 'nro-delegated-nro'  => 'https://bgp.potaroo.net/var/data/bgp/stats/nro/archive/2022/06/delegated-nro-20220618',
        // 'nro-delegated-nro-extended'  => 'https://bgp.potaroo.net/var/data/bgp/stats/nro/archive/2022/06/delegated-nro-extended-20220618',
        // 'nro-delegated-nro-extended-neu'  => 'https://bgp.potaroo.net/var/data/bgp/stats/nro/archive/2022/06/delegated-nro-extended-neu-20220618',
        'arin-delegated'  => 'https://bgp.potaroo.net/stats/arin/delegated',
        // 'arin-delegated-extended'  => 'https://bgp.potaroo.net/stats/arin/delegated-extended',
        // 'arin-delegated-extended-archive'  => 'https://bgp.potaroo.net/stats/arin/archive/2022/06/20220600-arin-delegated-extended',
        'arin-delegated'  => 'https://bgp.potaroo.net/stats/apnic/delegated',
        // 'iana-delegated-iana'  => 'https://bgp.potaroo.net/stats/iana/archive/2022/06/delegated-iana-20220618',
        // 'iana-delegated-iana-extended'  => 'https://bgp.potaroo.net/stats/iana/archive/2022/06/delegated-iana-extended-20220618',
        'arin-delegated-arin-extended'  => 'http://ftp.arin.net/pub/stats/arin/delegated-arin-extended-latest',
        'lacnic-delegated-lacnic-latest'  => 'http://ftp.apnic.net/stats/lacnic/delegated-lacnic-latest',
        'lacnic-delegated-lacnic-extended-latest'  => 'http://ftp.apnic.net/stats/lacnic/delegated-lacnic-extended-latest',
        'apnic-delegated-extended'  => 'https://bgp.potaroo.net/stats/apnic/delegated-extended',
        // 'apnic-delegated-extended-archive'  => 'https://bgp.potaroo.net/stats/apnic/archive/2022/06/20220600-apnic-delegated-extended',
        'apnic-delegated-apnic-latest'  => 'http://ftp.apnic.net/stats/apnic/delegated-apnic-latest',
        'apnic-delegated-apnic-ipv6-assigned-latest'  => 'http://ftp.apnic.net/stats/apnic/delegated-apnic-ipv6-assigned-latest',
        'apnic-delegated-apnic-extended-latest'  => 'http://ftp.apnic.net/stats/apnic/delegated-apnic-extended-latest',
        'apnic-legacy-apnic-latest'  => 'http://ftp.apnic.net/apnic/stats/apnic/legacy-apnic-latest',
        // 'afrinic-delegated-afrinic-latest'  => 'http://ftp.apnic.net/stats/afrinic/delegated-afrinic-latest',
        // 'ripecc-delegated-ripecc-latest'  => 'http://ftp.apnic.net/stats/ripe-ncc/delegated-ripencc-latest',
        'ripecc-delegated-ripencc-extended-latest'  => 'http://ftp.apnic.net/stats/ripe-ncc/delegated-ripencc-extended-latest',
        // 'nro-merged-stat'  => 'https://ftp.ripe.net/ripe/stats/nro-stats/latest/merged-stat',
        'nro-combined-stat'  => 'https://ftp.ripe.net/ripe/stats/nro-stats/latest/combined-stat',
        // 'nro-delegated-stats'  => 'https://ftp.ripe.net/ripe/stats/nro-stats/latest/nro-delegated-stats',
        'apnic-transfer-apnic-latest'  => 'http://ftp.apnic.net/transfers/apnic/transfer-apnic-latest',
        ]
    ];